all:
	g++ -o Creating_Payslip Creating_Payslip.cpp

dump:
	objdump -d Creating_Payslip > Creating_Payslip.asm

Clean:
	rm -f Creating_Payslip Creating_Payslip.asm

run: Creating_Payslip    
	./Creating_Payslip