all:
	g++ -o Solving_Quadratic_Equation Solving_Quadratic_Equation.cpp

dump:
	objdump -d Solving_Quadratic_Equation > Solving_Quadratic_Equation.asm

Clean:
	rm -f Solving_Quadratic_Equation Solving_Quadratic_Equation.asm

run: Solving_Quadratic_Equation    
	./Solving_Quadratic_Equation
